/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExpensePurchaseOrderItem {
    ID?: string;
    Qty?: number;
    Cost?: number;
    TypeID?: string;
    Name?: string;
    ExpensePurchaseOrderID?: string;
    IndexItem?: number;
    SATCompanyAccountID?: string;
}
