/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExpensePurchaseOrderItem } from './expensePurchaseOrderItem';


export interface ExpenseDetails {
    ID?: string;
    ProviderID?: string;
    ProviderName?: string;
    Status?: string;
    StatusCode?: number;
    CreationDate?: Date;
    CreditDays?: number;
    LocationID?: string;
    ClientID?: string;
    DepartmentID?: string;
    DocumentType?: number;
    DocumentNumber?: string;
    Comments?: string;
    VAT?: number;
    InvoiceID?: string;
    CurrencyID?: string;
    ExchangeRate?: number;
    UUID?: string;
    Series?: string;
    VATRetention?: number;
    ISRRetention?: number;
    IEPS?: number;
    Discount?: number;
    FiscalID?: string;
    ISRRetType?: number;
    RFC?: string;
    ExpensePurchaseOrderItems?: Array<ExpensePurchaseOrderItem>;
    DocumentTypeText?: string;
    CurrencyName?: string;
    ClientName?: string;
    LocationName?: string;
}
