/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewCreditNotesItem } from './newCreditNotesItem';


export interface NewCreditNote {
    Amount: number;
    BankAccount?: string;
    Comments?: string;
    Concept?: string;
    Unit?: string;
    CreditNotesItems?: Array<NewCreditNotesItem>;
    IEPSAmount?: number;
    InvoiceID: string;
    ISRRet?: number;
    PaymentMethod: number;
    PaymentTerms: number;
    SeriesID?: string;
    Type: number;
    VAT?: number;
    VATRet?: number;
}
