/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServiceDetails {
    Category1?: string;
    Category1ID?: string;
    Category2?: string;
    Category2ID?: string;
    Category3?: string;
    Category3ID?: string;
    ChargeVAT?: boolean;
    Code?: string;
    CreationDate?: Date;
    CurrencyCode?: string;
    CurrencyID?: string;
    Description?: string;
    ID?: string;
    Prices?: any;
    PricingType?: number;
    PricingTypeText?: string;
    SATCode?: number;
    SATUnit?: number;
    Title?: string;
    Unit?: string;
    VariableConcept?: boolean;
}
